AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS security workshop
Resources:
   
  securityWorkshopRestoreService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lambda/GuardDuty
      Timeout: 300
      Policies:
      - AmazonEC2FullAccess
      Tags:
        ProjectName: securityImmersionDay
